# Generated by Django 4.1.4 on 2022-12-19 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qHeader', models.CharField(max_length=200, verbose_name='QHeader')),
                ('qContent', models.CharField(max_length=500, verbose_name='QContent')),
                ('sHeader', models.CharField(max_length=200, verbose_name='sHeader')),
                ('sContent', models.CharField(max_length=500, verbose_name='sContent')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240, verbose_name='Name')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200, verbose_name='Password')),
                ('membership', models.CharField(default='free', max_length=10, verbose_name='Membership')),
                ('membershipD', models.DateField(verbose_name='MembershipD')),
                ('registrationDate', models.DateField(default=datetime.date(2022, 12, 18), verbose_name='Registration Date')),
            ],
        ),
    ]
